// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjxKJ2RenxNSLOpBFxFv5oHMA1GrzCiBs',
    appId: '1:580914414210:web:7f43665c0201d579d1ea9b',
    messagingSenderId: '580914414210',
    projectId: 'z-vertexai-for-firebase-01',
    authDomain: 'z-vertexai-for-firebase-01.firebaseapp.com',
    storageBucket: 'z-vertexai-for-firebase-01.appspot.com',
    measurementId: 'G-MGM13MKHCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWuB0TWc3iGU8avGFBrIJOCGRJr1Pmhhk',
    appId: '1:580914414210:android:b8b42252ff397c26d1ea9b',
    messagingSenderId: '580914414210',
    projectId: 'z-vertexai-for-firebase-01',
    storageBucket: 'z-vertexai-for-firebase-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGB2gc7WwAe7S9sdnKHC0A06I_nD7X_rE',
    appId: '1:580914414210:ios:eba92a33c3d09d30d1ea9b',
    messagingSenderId: '580914414210',
    projectId: 'z-vertexai-for-firebase-01',
    storageBucket: 'z-vertexai-for-firebase-01.appspot.com',
    iosBundleId: 'com.example.vertexai101',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGB2gc7WwAe7S9sdnKHC0A06I_nD7X_rE',
    appId: '1:580914414210:ios:eba92a33c3d09d30d1ea9b',
    messagingSenderId: '580914414210',
    projectId: 'z-vertexai-for-firebase-01',
    storageBucket: 'z-vertexai-for-firebase-01.appspot.com',
    iosBundleId: 'com.example.vertexai101',
  );

}